os:
    - linux
language: node_js
node_js:
    - "8.10.0"
before_install:
    - npm install -g npm
    - npm i -g makeshift && makeshift -s @bcoe -r https://registry.npmjs.org
    # Repo for Yarn
    - curl -o- -L https://yarnpkg.com/install.sh | bash
    - export PATH=$HOME/.yarn/bin:$PATH
install:
    - yarn install
    - yarn link
script:
    - yarn test
deploy:
  provider: npm
  email: angelo.mang@libero.it
  api_key: $NPM_TOKEN
  on:
    tags: true
